---
deployment_model:
  roles:
    - webserver
    - loadbalancer
    - monitor

  webserver:
    dummy: data
  loadbalancer:
    dummy: data
  monitor:
    vip: lb-1
    jenkins:
      password: Passw0rd
      password_hash: "$2a$10$P3jK32SmwCAZd8pBWg/x9uoO.WX0ugFROYmjbELLsJBjAjTJOaMRy"
      url: "http://localhost:8080" 
      user: service

  hosts:
    - hostname: web-1
      ip: 192.168.12.20
      ram: 1024
      role: webserver
      id: web-1
    - hostname: web-2
      ip: 192.168.12.21
      ram: 1024
      role: webserver
      id: web-2
    - hostname: lb-1
      ip: 192.168.12.30
      ram: 1024
      role: loadbalancer
      id: haproxy-1
    - hostname: jenkins-1
      ram: 4096
      role: monitor
      ip: 192.168.12.40
      id: jenkins-1
  

