attributes:
  server_ip:
    value: ''
    label: 'server_ip'
    description: 'ip for NFS share'
    weight: 25
    type: "text"
  path_to_mnt:
    value: ''
    label: 'path to server'
    description: 'NFS path to server side share directory'
    weight: 30
    type: "text"
